source 'https://rubygems.org'

gem 'rails', '4.2.1'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'therubyracer', platforms: :ruby

gem 'turbolinks'
gem 'jbuilder', '~> 2.0'

group :development, :test do
  gem 'pry'
  gem 'spring'
end

gem 'browserify-rails'
