defaults: &defaults
  enabled: true
  fog_provider: 'AWS'
  aws_access_key_id: 'AKIAI5HJ7EYXJONN2XGQ'
  aws_secret_access_key: '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'
  fog_region: 'eu-west-1'
  existing_remote_files: keep
  gzip_compression: true
  initialize_on_precompile: true
  run_on_precompile: true

development:
  enabled: false

test:
  enabled: false

production:
  <<: *defaults
  fog_directory: 'sslcatch'
