mysql: &mysql
  adapter: mysql2
  encoding: utf8
  host: 127.0.0.1
  port: 3306
  username: root
  password: root

development:
  <<: *mysql
  database: ttt_development

test: &test
  <<: *mysql
  database: ttt_test
