mysql: &mysql
  adapter: mysql2
  encoding: utf8
  host: 127.0.0.1
  port: 3306
  username: root
  password: root

development:
  <<: *mysql
  database: sslcatch_development

test: &test
  <<: *mysql
  database: sslcatch_test

production:
  <<: *mysql
  host: db1-pivotalcf-made.chgtsengn3gn.us-east-1.rds.amazonaws.com
  username: sslcatch_prod
  password: rE4Y3PwBaNjawK2Q
  database: sslcatch_production
  pool: 25
