// Generated by CoffeeScript 1.7.1
var Teaminator, isIdealSize;

isIdealSize = function(people, maxSize) {
  var groups;
  groups = people.chunk(maxSize);
  return (groups[0].length - groups[groups.length - 1].length) <= 1;
};

Teaminator = {
  group: function(people) {
    var i, maxSize;
    maxSize = 5;
    i = maxSize;
    while (i >= 0) {
      if (isIdealSize(people, i)) {
        return people.chunk(i);
      }
      i--;
    }
  },
  groupRandomly: function(people) {
    return Teaminator.group(people.shuffle());
  }
};

Array.prototype.chunk = function(chunkSize) {
  var array;
  array = this;
  return [].concat.apply([], array.map(function(elem, i) {
    if (i % chunkSize) {
      return [];
    } else {
      return [array.slice(i, i + chunkSize)];
    }
  }));
};

Array.prototype.shuffle = function() {
  var currentIndex, randomIndex, temporaryValue;
  currentIndex = this.length;
  temporaryValue = void 0;
  randomIndex = void 0;
  while (0 !== currentIndex) {
    randomIndex = Math.floor(Math.random() * currentIndex);
    currentIndex -= 1;
    temporaryValue = this[currentIndex];
    this[currentIndex] = this[randomIndex];
    this[randomIndex] = temporaryValue;
  }
  return this;
};
