source 'https://rubygems.org'
ruby '2.1.2'

gem 'asset_sync',                     '1.1.0'
gem 'compass-rails',                  '2.0.4'
gem 'cf-deploy',                      '0.1.4'
gem 'dalli',                          '2.7.2'
gem 'daemons',                        '1.2.2'
gem 'delayed_job_active_record',      '4.0.3'
gem 'delayed_job_web',                '1.2.10'
gem 'devise',                         '3.4.1'
gem 'gssapi',                         '1.2.0'
gem 'httpi',                          '2.4.0'
gem 'jquery-rails',                   '4.0.3'
gem 'libv8',                          '3.16.14.7'
gem 'mysql2',                         '0.3.16'
gem 'newrelic_rpm',                   '3.11.0.283'
gem 'nokogiri',                       '1.6.6.2'
gem 'puma',                           '2.11.0'
gem 'rails',                          '4.2.0'
gem 'sass-rails',                     '5.0.1'
gem 'susy',                           '2.2.2'
gem 'therubyracer',                   '0.12.1'
gem 'turbolinks',                     '2.2.3'
gem 'uglifier',                       '2.5.3'
gem 'unf',                            '0.1.4'
gem 'rb-readline'

group :development, :test do
  gem 'scss-lint',                    '~> 0.37.0'
end

group :development do
  gem 'better_errors',                '~> 1.1.0'
  gem 'bullet',                       '~> 4.14.2'
  gem 'i18n-tasks',                   '~> 0.8.2'
  gem 'pry-rails',                    '~> 0.3.3'
  gem 'quiet_assets',                 '~> 1.1.0'
  gem 'spring',                       '~> 1.2.0'
  gem 'spring-commands-rspec',        '~> 1.0.2'
end

group :test do
  gem 'brakeman'                      # Always latest
  gem 'cane',                         '~> 2.6.2'
  gem 'capybara',                     '~> 2.4.1'
  gem 'factory_girl',                 '~> 4.5.0'
  gem 'ffaker',                       '~> 1.32.1'
  gem 'rspec',                        '~> 3.2.0'
  gem 'rspec-its',                    '~> 1.0.1'
  gem 'rspec-rails',                  '~> 3.2.1'
  gem 'rspec_junit_formatter',        '~> 0.2.0'
  gem 'simplecov',                    '~> 0.9.0'
  gem 'simplecov-rcov',               '~> 0.2.3'
  gem 'tailor',                       '~> 1.4.1'
  gem 'vcr',                          '~> 2.9.2'
  gem 'webmock',                      '~> 1.19.0'
end
