// Generated by CoffeeScript 1.7.1
describe('Teaminator', function() {
  var group, groupRandomly;
  group = Teaminator.group, groupRandomly = Teaminator.groupRandomly;
  describe('.group', function() {
    describe('when given eight people', function() {
      var groups, people;
      people = ['emile', 'seb', 'luke', 'matt', 'fareed', 'scoot', 'chris', 'rory'];
      groups = group(people);
      it('should return two groups', function() {
        return expect(groups.length).toEqual(2);
      });
      return it('should return groups of four', function() {
        return $.each(groups, function(i) {
          return expect(groups[i].length).toEqual(4);
        });
      });
    });
    describe('when given nine people', function() {
      var groups, people;
      people = ['emile', 'seb', 'luke', 'matt', 'fareed', 'scoot', 'chris', 'rory', 'jeff'];
      groups = group(people);
      it('should return two groups', function() {
        return expect(groups.length).toEqual(2);
      });
      it('should return first group with five people', function() {
        return expect(groups[0].length).toEqual(5);
      });
      return it('should return second group with four people', function() {
        return expect(groups[1].length).toEqual(4);
      });
    });
    return describe('when given eleven people', function() {
      var groups, people;
      people = ['emile', 'seb', 'luke', 'matt', 'fareed', 'scoot', 'chris', 'rory', 'jeff', 'bob', 'dean'];
      groups = group(people);
      it('should return three groups', function() {
        return expect(groups.length).toEqual(3);
      });
      it('should return first group with four people', function() {
        return expect(groups[0].length).toEqual(4);
      });
      it('should return second group with four people', function() {
        return expect(groups[1].length).toEqual(4);
      });
      return it('should return third group with three people', function() {
        return expect(groups[2].length).toEqual(3);
      });
    });
  });
  return describe('.groupRandomly', function() {
    var people;
    people = ['emile', 'seb', 'luke', 'matt', 'fareed', 'scoot', 'chris', 'rory', 'jeff'];
    return it('should not return the same groups on subsequent calls', function() {
      var first_group, second_group;
      first_group = groupRandomly(people);
      second_group = groupRandomly(people);
      return expect(first_group).not.toEqual(second_group);
    });
  });
});
